#!/bin/sh

set -e
set -x

rm -rf Makefile
rm -rf Makefile.in
rm -rf aclocal.m4
rm -rf autom4te.cache
rm -rf compile
rm -rf config.guess
rm -rf config.h
rm -rf config.h.in
rm -rf config.h.in~
rm -rf config.log
rm -rf config.status
rm -rf config.sub
rm -rf configure
rm -rf depcomp
rm -rf tr50/Makefile
rm -rf tr50/Makefile.in
rm -rf install-sh
rm -rf libtr50/.deps/
rm -rf libtr50/.libs/
rm -rf libtr50/Makefile
rm -rf libtr50/Makefile.in
rm -rf libtool
rm -rf ltmain.sh
rm -rf build-aux
rm -f m4/libtool.m4
rm -f m4/ltoptions.m4
rm -f m4/ltsugar.m4
rm -f m4/ltversion.m4
rm -f m4/lt~obsolete.m4
rm -rf missing
rm -rf stamp-h1
rm -rf libtr50/.deps
rm -rf libtr50/mqtt/.deps
rm -rf libtr50/mqtt/.dirstamp
rm -rf libtr50/util/.deps
rm -rf libtr50/util/linux/.deps
rm -rf libtr50/util/linux/.dirstamp
rm -rf libtr50/wrappers/.deps
rm -rf libtr50/wrappers/.dirstamp
rm -rf include/Makefile.in
rm -rf tr50/internal/Makefile.in
rm -rf tr50/mqtt/Makefile.in
rm -rf tr50/util/Makefile.in
rm -rf tr50/wrappers/Makefile.in
